services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports: 
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
  
  redis-test:
    image: redis:7
    ports: 
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  celery-test:
    build:
      context: .
      target: runtime-test
    command: python -m celery -A core worker --loglevel=info --concurrency=2
    volumes: 
      - .:/app
    env_file: .env
    depends_on:
      redis-test:
        condition: service_healthy
      db-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3

  web-test:  # test
    build:
      context: .
      target: runtime-test
    command: pytest -v --maxfail=1 --disable-warnings
    env_file: .env
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      celery-test:
        condition: service_healthy

volumes:
  postgres_data_test:
  static_volume: