services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  redis-test:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
  celery-prod:
    build:
      context: .
      target: runtime-prod
    command: python -m celery -A core worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis-test:
        condition: service_healthy
      db-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3

  web-prod:  # prod
    build:
      context: .
      target: runtime-prod
    command: >
      sh -c "python manage.py collectstatic --noinput --settings=core.settings &&
        gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      celery-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 5
  nginx-prod:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web-prod

  

  



volumes:
  postgres_data_prod:
  static_volume: