services:
  web-test:  # test
    build:
      context: .
      target: runtime-test
    command: pytest
    env_file: .env
    depends_on:
      - db-test

  db-test:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

volumes:
  postgres_data_test:
  static_volume: