services:
  db:
    image: postgres:15
    env_file:
      - conf/dev/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
  
  init-static:
    image: web:${TAG}
    command: python manage.py collectstatic --noinput
    env_file:
      - .env
    volumes: 
      - static_volume:/app/staticfiles
    depends_on: 
      db:
        condition: service_healthy

  web:  
    image: web:${TAG}  
    env_file: 
      - .env
    depends_on:
      init-static:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  celery:
    image: celery:${TAG}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3
  
  celery-beat:
    image: celery-beat:${TAG}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  nginx:
    image: nginx:${TAG}
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - static_volume:/app/staticfiles:ro 
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  static_volume: