services:
  db:
    image: postgres:15
    env_file: conf/test/.env
    ports: 
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
  
  redis:
    image: redis:7
    ports: 
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  celery:
    build:
      context: .
      target: runtime-test
    command: python -m celery -A core worker --loglevel=info --concurrency=2
    volumes: 
      - .:/app
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3
  
  celery-beat:
    build:
      context: .
      target: runtime-test
    command: celery -A core beat --loglevel=INFO
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:  # test
    build:
      context: .
      target: runtime-test
    command: pytest -v --maxfail=1 --disable-warnings
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy