# Generated by Django 5.2.2 on 2025-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('threads', '0007_remove_user_is_repost_follow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['repost_of_content_type', 'repost_of_content_item_id'], name='app_comment_repost__932f99_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['repost_of_content_type', 'repost_of_content_item_id'], name='app_post_repost__40a4e3_idx'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='app_post',
        ),
    ]
