name: Prod Smoke Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    services:
        docker: # optional，GitHub 已預裝 Docker
          image: docker:24.0.6
          options: --privileged
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env vars
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          DATABASE_USER: ${{ vars.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ vars.DATABASE_HOST }}
          DATABASE_PORT: ${{ vars.DATABASE_PORT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
            echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> .env
            echo "DATABASE_NAME=${DATABASE_NAME}" >> .env
            echo "DATABASE_USER=${DATABASE_USER}" >> .env
            echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" >> .env
            echo "DATABASE_HOST=${DATABASE_HOST}" >> .env
            echo "DATABASE_PORT=${DATABASE_PORT}" >> .env
            echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
            echo "SERPAPI_API_KEY=${SERPAPI_API_KEY}" >> .env
            echo "POSTGRES_DB=${POSTGRES_DB}" >> backend/.env
            echo "POSTGRES_USER=${POSTGRES_USER}" >> backend/.env
            echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> backend/.env
      
      - name: Start containers to verify services
        run: |
            docker compose -f docker-compose-prod.yml up --build --detach --wait --wait-timeout 60
        working-directory: ./backend

      - name: Tear down containers before build
        run: docker compose -f docker-compose-prod.yml down --volumes
        working-directory: ./backend

      - name: Build Docker image with Compose
        run: |
          docker build -t web-prod:latest .
        working-directory: ./backend
        
      - name: Debug image list
        run: docker images